#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

JAVA_REPO=trusty
NODE_VERSION=6.x

echo "Pre-config..."

apt-get update >/dev/null

apt-get -y install dirmngr >/dev/null
apt-get -y install curl >/dev/null

echo "Adding Java 8 repo"

echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu ${JAVA_REPO} main" | tee /etc/apt/sources.list.d/webupd8team-java.list

echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu ${JAVA_REPO} main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 >/dev/null

apt-get update >/dev/null

echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

echo "Adding NodeJS ${NODE_VERSION} repo"
curl --silent --location https://deb.nodesource.com/setup_${NODE_VERSION} | bash -
apt-get -y update >/dev/null


