#!/bin/sh

JAVA_REPO=trusty
NODE_VERSION=6.x

echo "Adding Java 8 repo"

echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu ${JAVA_REPO} main" | tee /etc/apt/sources.list.d/webupd8team-java.list

echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 >/dev/null

apt-get update >/dev/null

echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

echo "Adding NodeJS ${NODE_VERSION} repo"
apt-get install curl
curl --silent --location https://deb.nodesource.com/setup_${NODE_VERSION} | sudo bash -
apt-get update >/dev/null


