#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

NODE_VERSION=12.x

echo "Pre-config..."

apt-get update >/dev/null

apt-get -y install dirmngr >/dev/null
apt-get -y install curl >/dev/null

echo "Adding NodeJS ${NODE_VERSION} repo"
curl --silent --location https://deb.nodesource.com/setup_${NODE_VERSION} | bash -
apt-get -y update >/dev/null


