#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "Installing packages"

apt-get -y install sudo network-manager iptables nodejs \
python3 tor tor-geoipdb obfsproxy obfs4proxy privoxy \
haveged shellinabox links dnsutils sed ifupdown \
python3-pexpect python3-requests python3-lxml python3-netifaces \
openjdk-8-jre-headless



