#!/bin/sh

echo "Installing packages"

apt-get -y install sudo network-manager iptables nodejs \
python3 tor tor-geoipdb obfsproxy obfs4proxy privoxy \
haveged shellinabox links \
python3-pexpect python3-requests python3-lxml python3-netifaces \
oracle-java8-installer "oracle-java8-set-default"



