#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "Patching nmcli to run without root credentials"
NMCLILOCATION=$(which nmcli)
chmod u+s,a-w $NMCLILOCATION

echo "Creating /usr/lib/systemd/system if needed"
if [ ! -d "/usr/lib/systemd/system" ]; then
  mkdir -p /usr/lib/systemd/system
fi

